spring:
  application:
    name: ins-gateway
  cloud:
    gateway:
      routes:
      - id: ins-user-service
        uri: lb://INS-USER-SERVICE
        predicates:
        - Path=/api/user/**
        filters:
        - StripPrefix=1
      - id: ins-moment-service
        uri: lb://INS-MOMENT-SERVICE
        predicates:
        - Path=/api/moment/**
        filters:
        - StripPrefix=1
      - id: ins-collect-service
        uri: lb://INS-COLLECT-SERVICE
        predicates:
        - Path=/api/collect/**
        filters:
        - StripPrefix=1
server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6000/eureka/


