spring:
  application:
    name: ins-gateway
  cloud:
    gateway:
      routes:
      - id: ins-user-service
        uri: lb://INS-USER-SERVICE
        predicates:
        - Path=/api/user/**
        filters:
        - StripPrefix=1
server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6000/eureka/


