server:
  port: 6011
spring:
  application:
    name: ins-message-service
  datasource:
    url: jdbc:mysql://47.100.97.46:3306/ins_message?serverTimezone=GMT%2B8&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6000/eureka/
sms:
  aliyun:
    accessKeyId: LTAIPylXSyjSzvHF # 你自己的accessKeyId
    accessKeySecret: dl0fLVNu3D31x4sFkzgpML6LMX8AYc # 你自己的AccessKeySecret
    regionId: cn-hangzhou
    domain: dysmsapi.aliyuncs.com
  available:
  - aliyun #优先使用阿里云

