server:
  port: 6011
spring:
  application:
    name: ins-message-service
  datasource:
    url: jdbc:mysql://47.100.97.46:3306/ins_message?serverTimezone=GMT%2B8&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  rabbitmq:
    host: 47.100.97.46
    username: admin
    password: admin
    port: 5672
    virtual-host: my_vhost
  #邮箱配置
  mail:
    host: smtp.qq.com
    username: 302827797@qq.com
    #QQ邮箱的授权码
    password: rwhbfegjfleqbiab
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6000/eureka/
sms:
  aliyun:
    accessKeyId: LTAIPylXSyjSzvHF # 你自己的accessKeyId
    accessKeySecret: dl0fLVNu3D31x4sFkzgpML6LMX8AYc # 你自己的AccessKeySecret
    regionId: cn-hangzhou
    domain: dysmsapi.aliyuncs.com
  available:
  - aliyun_sms #优先使用阿里云
email:
  qq:
    sendFrom: 302827797@qq.com
  available:
  - qq.email #优先使用QQ邮箱


